apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  storageClassName: nfs      
  capacity:                  # PV容量
    storage: 1Gi
  accessModes:               # 访问模式
  - ReadWriteOnce
  nfs:
    path: /root/web1
    server: "172.16.201.134"
  volumeMode: Filesystem
