kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
#  namespace: production-pppharmapack
  labels:
    app: redis
data:
  redis.conf: |-
    dir /data
    port 6379
    bind 0.0.0.0
    appendonly yes
    protected-mode no
    requirepass zisefeizhu
    pidfile /data/redis-6379.pid
