kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-nfs-provisioner2
subjects:
  - kind: ServiceAccount
    name: nfs-provisioner2
    namespace: default
roleRef:
  kind: ClusterRole
  name: nfs-provisioner-runner2
  apiGroup: rbac.authorization.k8s.io
