apiVersion: v1
kind: Service
metadata:
  name: spring-k8s
spec:
  selector:
    app: spring-k8s
  type: NodePort
  ports:
    - nodePort: 30008
      port: 80
      protocol: TCP
      targetPort: 8080
  sessionAffinity: ClientIP
