apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:            
    storage: 1Gi
  volumeMode: Filesystem  
  accessModes:           
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs                
  nfs:
    path: /nfs/pv1
    server: 172.16.201.134
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  capacity:            
    storage: 2Gi
  volumeMode: Filesystem  
  accessModes:           
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /nfs/pv2
    server: 172.16.201.134
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:            
    storage: 3Gi
  volumeMode: Filesystem  
  accessModes:           
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-mysql
  nfs:
    path: /nfs/pv3
    server: 172.16.201.134
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0004
spec:
  capacity:            
    storage: 5Gi
  volumeMode: Filesystem  
  accessModes:           
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-nginx
  nfs:
    path: /nfs/pv4
    server: 172.16.201.134
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0005
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-php
  nfs:
    path: /nfs/pv5
    server: 172.16.201.134
