apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas-zk
#  annotations:
#    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/nfs
reclaimPolicy: Delete
parameters:
  archiveOnDelete: "false"
