apiVersion: v1
kind: PersistentVolume
metadata:
    name: kafka-zk01
spec:
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    storageClassName: nas-zk
    nfs:
      path: /root/kafkadata/zkdata01
      server: 172.16.201.134

---

apiVersion: v1
kind: PersistentVolume
metadata:
    name: kafka-zk02
spec:
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    storageClassName: nas-zk
    nfs:
      path: /root/kafkadata/zkdata02
      server: 172.16.201.134

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: kafka-zk03
spec:
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    storageClassName: nas-zk
    nfs:
      path: /root/kafkadata/zkdata03
      server: 172.16.201.134
