apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus3
  name: nexus3
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 8081
    name: web-ui
  - port: 5000
    targetPort: 5000
    nodePort: 5000
    name: docker-group
  - port: 8889
    targetPort: 8889
    nodePort: 8889
    name: docker-push
  selector:
    app: nexus3
